import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { after, before, describe, test } from 'node:test';

const BIN = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'bin', 'metamask-skills.mjs');
const INSTALL = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'tools', 'install');
const MANAGED_BANNER =
  '<!-- DO NOT EDIT — Generated by MetaMask skills tools/install. Changes will be overwritten on next sync. Edit the source skill at https://github.com/MetaMask/skills (public) or https://github.com/Consensys/skills (private overlay) instead. -->';

function runCli(args, env = {}) {
  return spawnSync(process.execPath, [BIN, ...args], {
    encoding: 'utf8',
    maxBuffer: 16 * 1024 * 1024,
    // Neutralize any source-dir env vars from the host shell so tests are deterministic.
    env: {
      ...process.env,
      METAMASK_SKILLS_DIR: '',
      CONSENSYS_SKILLS_DIR: '',
      SKILLS_PRUNE_STALE: '',
      ...env,
    },
  });
}

describe('CLI entrypoint', () => {
  test('--help prints usage and exits 0', () => {
    const result = runCli(['--help']);
    assert.equal(result.status, 0);
    assert.match(result.stdout, /MetaMask skills CLI/u);
    assert.match(result.stdout, /metamask-skills sync/u);
  });

  test('no command prints usage and exits 0', () => {
    const result = runCli([]);
    assert.equal(result.status, 0);
    assert.match(result.stdout, /Usage:/u);
  });

  test('unknown command exits 1 with error', () => {
    const result = runCli(['frobnicate']);
    assert.equal(result.status, 1);
    assert.match(result.stderr, /Unknown command: frobnicate/u);
  });

  test('runs when invoked through a symlinked bin (npm install layout)', () => {
    const dir = mkdtempSync(path.join(os.tmpdir(), 'mms-bin-'));
    const link = path.join(dir, 'metamask-skills');
    symlinkSync(BIN, link);
    const result = spawnSync(process.execPath, [link, '--help'], { encoding: 'utf8' });
    rmSync(dir, { recursive: true, force: true });
    assert.equal(result.status, 0);
    assert.match(result.stdout, /MetaMask skills CLI/u);
  });
});

describe('CLI list against a fixture source', () => {
  let root;
  let source;

  before(() => {
    root = mkdtempSync(path.join(os.tmpdir(), 'mms-cli-'));
    source = path.join(root, 'skills-source');
    const skillDir = path.join(source, 'domains', 'testing', 'skills', 'unit-testing');
    mkdirSync(path.join(skillDir, 'repos'), { recursive: true });
    mkdirSync(path.join(source, 'tools'), { recursive: true });
    writeFileSync(
      path.join(skillDir, 'skill.md'),
      ['---', 'name: unit-testing', 'description: Write unit tests', 'maturity: stable', '---', 'Body.'].join('\n'),
    );
  });

  after(() => {
    rmSync(root, { recursive: true, force: true });
  });

  test('list --json emits valid JSON scoped to the configured source', () => {
    const result = runCli(['list', '--json', '--target', root, '--repo', 'core'], {
      METAMASK_SKILLS_DIR: source,
    });
    assert.equal(result.status, 0);
    const parsed = JSON.parse(result.stdout);
    assert.equal(parsed.repo, 'core');
    assert.deepEqual(parsed.sources, [source]);
    assert.deepEqual(parsed.skills.map((s) => s.id), ['testing/unit-testing']);
  });

  test('search narrows results and exits 0', () => {
    const result = runCli(['search', 'unit', '--json', '--target', root], {
      METAMASK_SKILLS_DIR: source,
    });
    assert.equal(result.status, 0);
    const parsed = JSON.parse(result.stdout);
    assert.equal(parsed.skills.length, 1);
    assert.equal(parsed.query, 'unit');
  });
});

describe('managed skill pruning', () => {
  let root;
  let source;
  let target;

  before(() => {
    root = mkdtempSync(path.join(os.tmpdir(), 'mms-prune-'));
    source = path.join(root, 'source');
    target = path.join(root, 'target');
    const skillDir = path.join(source, 'domains', 'testing', 'skills', 'current');
    mkdirSync(skillDir, { recursive: true });
    mkdirSync(path.join(source, 'tools'), { recursive: true });
    symlinkSync(INSTALL, path.join(source, 'tools', 'install'));
    mkdirSync(target, { recursive: true });
    writeFileSync(
      path.join(skillDir, 'skill.md'),
      ['---', 'name: current', 'description: Current skill', 'maturity: stable', '---', 'Body.'].join('\n'),
    );
  });

  after(() => {
    rmSync(root, { recursive: true, force: true });
  });

  function writeInstalledSkill(base, name, file, managed, installTarget = target) {
    const dir = path.join(installTarget, base, name);
    mkdirSync(dir, { recursive: true });
    writeFileSync(path.join(dir, file), managed ? `${MANAGED_BANNER}\nBody.\n` : 'Hand-authored.\n');
    return dir;
  }

  test('removes only stale installer-managed skills across project targets', () => {
    const targets = [
      ['.claude/skills', 'SKILL.md'],
      ['.cursor/rules', 'RULE.md'],
      ['.agents/skills', 'SKILL.md'],
    ];
    const stale = [];
    const custom = [];
    for (const [base, file] of targets) {
      stale.push(writeInstalledSkill(base, 'mms-stale', file, true));
      custom.push(writeInstalledSkill(base, 'mms-custom', file, false));
    }

    const result = spawnSync(
      '/bin/bash',
      [INSTALL, '--target', target, '--repo', 'core', '--source', source, '--prune-stale'],
      { encoding: 'utf8' },
    );

    assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
    for (const dir of stale) assert.equal(existsSync(dir), false);
    for (const dir of custom) assert.equal(existsSync(dir), true);
    for (const [base] of targets) {
      assert.equal(existsSync(path.join(target, base, 'mms-current')), true);
    }
  });

  test('dry-run reports but preserves a stale managed skill', () => {
    const stale = writeInstalledSkill('.agents/skills', 'mms-dry-run-stale', 'SKILL.md', true);
    const result = spawnSync(
      '/bin/bash',
      [INSTALL, '--target', target, '--repo', 'core', '--source', source, '--prune-stale', '--dry-run'],
      { encoding: 'utf8' },
    );

    assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
    assert.match(result.stdout, /mms-dry-run-stale \(remove stale managed skill\)/u);
    assert.equal(existsSync(stale), true);
  });

  test('handles an empty expected selection under the supported system Bash', () => {
    const stale = writeInstalledSkill('.agents/skills', 'mms-empty-selection', 'SKILL.md', true);
    const result = spawnSync(
      '/bin/bash',
      [
        INSTALL,
        '--target',
        target,
        '--repo',
        'core',
        '--source',
        source,
        '--domain',
        'not-selected',
        '--prune-stale',
        '--dry-run',
      ],
      { encoding: 'utf8' },
    );

    assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
    assert.match(result.stdout, /mms-empty-selection \(remove stale managed skill\)/u);
    assert.equal(existsSync(stale), true);
  });

  test('wires prune through the public sync CLI flag and accepted environment values only', () => {
    const fromFlag = writeInstalledSkill('.agents/skills', 'mms-cli-flag-stale', 'SKILL.md', true);
    const flagResult = runCli(['sync', '--target', target, '--repo', 'core', '--prune-stale'], {
      METAMASK_SKILLS_DIR: source,
    });

    assert.equal(flagResult.status, 0, `${flagResult.stdout}\n${flagResult.stderr}`);
    assert.equal(existsSync(fromFlag), false);

    const fromEnv = writeInstalledSkill('.agents/skills', 'mms-cli-env-stale', 'SKILL.md', true);
    const envResult = runCli(['sync', '--target', target, '--repo', 'core'], {
      METAMASK_SKILLS_DIR: source,
      SKILLS_PRUNE_STALE: '1',
    });

    assert.equal(envResult.status, 0, `${envResult.stdout}\n${envResult.stderr}`);
    assert.equal(existsSync(fromEnv), false);

    const fromDisabledEnv = writeInstalledSkill('.agents/skills', 'mms-cli-disabled-env-stale', 'SKILL.md', true);
    const disabledEnvResult = runCli(['sync', '--target', target, '--repo', 'core'], {
      METAMASK_SKILLS_DIR: source,
      SKILLS_PRUNE_STALE: '0',
    });

    assert.equal(disabledEnvResult.status, 0, `${disabledEnvResult.stdout}\n${disabledEnvResult.stderr}`);
    assert.equal(existsSync(fromDisabledEnv), true);
  });

  test('--save preserves configured public and private source paths', () => {
    const privateSource = path.join(root, 'private-source');
    mkdirSync(path.join(privateSource, 'domains'), { recursive: true });
    mkdirSync(path.join(privateSource, 'tools'), { recursive: true });
    symlinkSync(INSTALL, path.join(privateSource, 'tools', 'install'));
    writeFileSync(
      path.join(target, '.skills.local'),
      `export METAMASK_SKILLS_DIR=${source}\nCONSENSYS_SKILLS_DIR='${privateSource}'\nSKILLS_DOMAINS=testing\n`,
    );

    const result = runCli(
      ['sync', '--target', target, '--repo', 'core', '--include', 'testing/current', '--save', '--dry-run'],
      { METAMASK_SKILLS_DIR: source, CONSENSYS_SKILLS_DIR: privateSource },
    );

    assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
    const saved = readFileSync(path.join(target, '.skills.local'), 'utf8');
    assert.match(saved, new RegExp(`^export METAMASK_SKILLS_DIR=${source}$`, 'mu'));
    assert.match(saved, new RegExp(`^CONSENSYS_SKILLS_DIR='${privateSource}'$`, 'mu'));
    assert.match(saved, /^SKILLS_INCLUDE=testing\/current$/mu);
  });

  test('does not prune stale skills when installation fails', () => {
    const failingTarget = path.join(root, 'failing-target');
    const stale = writeInstalledSkill('.agents/skills', 'mms-preserved-on-failure', 'SKILL.md', true, failingTarget);
    const blockingPath = path.join(failingTarget, '.claude', 'skills', 'mms-current');
    mkdirSync(path.dirname(blockingPath), { recursive: true });
    writeFileSync(blockingPath, 'Blocks creation of the managed skill directory.\n');

    const result = spawnSync(
      '/bin/bash',
      [INSTALL, '--target', failingTarget, '--repo', 'core', '--source', source, '--prune-stale'],
      { encoding: 'utf8' },
    );

    assert.notEqual(result.status, 0);
    assert.equal(existsSync(stale), true);
  });
});

describe('installed knowledge references resolve', () => {
  let root;
  let source;
  let target;

  before(() => {
    root = mkdtempSync(path.join(os.tmpdir(), 'mms-knowledge-refs-'));
    source = path.join(root, 'source');
    target = path.join(root, 'target');
    mkdirSync(path.join(source, 'tools'), { recursive: true });
    symlinkSync(INSTALL, path.join(source, 'tools', 'install'));
    mkdirSync(target, { recursive: true });

    // The fixture carries a real CONSUMER: a skill body that cites a knowledge file
    // the way shipped skills actually do — skill-relative `knowledge/<file>`. A fixture
    // without one cannot exhibit a layout regression, which is how MetaMask/skills#87
    // shipped a change that stranded 12 such references while every test passed.
    const knowledge = path.join(source, 'domains', 'testing', 'knowledge');
    mkdirSync(knowledge, { recursive: true });
    writeFileSync(path.join(knowledge, 'alpha.md'), '# Alpha\n');
    const dir = path.join(source, 'domains', 'testing', 'skills', 'consumer');
    mkdirSync(dir, { recursive: true });
    writeFileSync(
      path.join(dir, 'skill.md'),
      [
        '---',
        'name: consumer',
        'description: Cites a domain knowledge file',
        'maturity: stable',
        '---',
        'Read [alpha](knowledge/alpha.md) before starting.',
      ].join('\n'),
    );
  });

  after(() => {
    rmSync(root, { recursive: true, force: true });
  });

  test('every knowledge/ reference in an emitted skill resolves on disk', () => {
    const result = spawnSync(
      'bash',
      [INSTALL, '--target', target, '--repo', 'core', '--source', source],
      { encoding: 'utf8' },
    );
    assert.equal(result.status, 0, result.stderr);

    const emitted = [
      ['.claude/skills', 'mms-consumer', 'SKILL.md'],
      ['.cursor/rules', 'mms-consumer', 'RULE.md'],
      ['.agents/skills', 'mms-consumer', 'SKILL.md'],
    ];
    for (const [base, name, file] of emitted) {
      const skillDir = path.join(target, base, name);
      const body = readFileSync(path.join(skillDir, file), 'utf8');
      const refs = [...body.matchAll(/\]\((knowledge\/[\w.-]+)\)/gu)].map((m) => m[1]);
      assert.ok(refs.length > 0, `${base}/${name}: expected a knowledge reference in the emitted body`);
      for (const ref of refs) {
        assert.ok(
          existsSync(path.join(skillDir, ref)),
          `${base}/${name}: dangling knowledge reference ${ref} — the body cites it but install did not place it there`,
        );
      }
    }
  });
});

describe('corpus: knowledge citations resolve within their own domain', () => {
  // `knowledge/` is copied per DOMAIN, so a skill can only cite files from its own
  // domain's knowledge dir. A citation naming another domain's file can never resolve
  // for any consumer or operator — the skill installs fine and the reference dangles.
  //
  // Known-unresolved, tracked separately; the list must only ever shrink. Each entry is
  // a cross-domain citation of testing/knowledge/testing-layers.md, which the installer
  // has no way to deliver into these domains.
  const KNOWN_UNRESOLVED = new Set([
    'domains/coding/skills/coding-guidelines/repos/metamask-mobile.md → knowledge/testing-layers.md',
    'domains/perps/skills/perps-review-pr/skill.md → knowledge/testing-layers.md',
    'domains/pr-workflow/skills/pr-guidelines/repos/metamask-mobile.md → knowledge/testing-layers.md',
    'domains/pr-workflow/skills/pr-readiness-check/repos/metamask-mobile.md → knowledge/testing-layers.md',
  ]);

  function collectCitations(domainsDir) {
    const found = [];
    const walk = (dir) => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) walk(full);
        else if (entry.isFile() && entry.name.endsWith('.md')) {
          const rel = path.relative(path.join(domainsDir, '..'), full).split(path.sep).join('/');
          if (!rel.includes('/skills/')) continue;
          const domain = rel.split('/')[1];
          const body = readFileSync(full, 'utf8');
          for (const m of body.matchAll(/\]\((knowledge\/[\w.-]+\.md)\)|`(knowledge\/[\w.-]+\.md)`/gu)) {
            const ref = m[1] || m[2];
            found.push({ rel, domain, ref, key: `${rel} → ${ref}` });
          }
        }
      }
    };
    walk(domainsDir);
    return found;
  }

  test('no skill cites a knowledge file its own domain does not ship', () => {
    const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
    const domainsDir = path.join(repoRoot, 'domains');
    const unresolved = collectCitations(domainsDir).filter(
      (c) => !existsSync(path.join(domainsDir, c.domain, c.ref)),
    );

    const unexpected = unresolved.filter((c) => !KNOWN_UNRESOLVED.has(c.key));
    assert.deepEqual(
      unexpected.map((c) => c.key),
      [],
      'new dangling knowledge citation(s) — a skill may only cite its own domain\'s knowledge',
    );
  });

  test('the known-unresolved list has no stale entries', () => {
    const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
    const domainsDir = path.join(repoRoot, 'domains');
    const stillBroken = new Set(
      collectCitations(domainsDir)
        .filter((c) => !existsSync(path.join(domainsDir, c.domain, c.ref)))
        .map((c) => c.key),
    );
    const fixed = [...KNOWN_UNRESOLVED].filter((k) => !stillBroken.has(k));
    assert.deepEqual(fixed, [], 'these citations now resolve — remove them from KNOWN_UNRESOLVED');
  });
});
