import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { after, before, describe, test } from 'node:test';

const BIN = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'bin', 'metamask-skills.mjs');
const INSTALL = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'tools', 'install');
const MANAGED_BANNER =
  '<!-- DO NOT EDIT — Generated by MetaMask skills tools/install. Changes will be overwritten on next sync. Edit the source skill at https://github.com/MetaMask/skills (public) or https://github.com/Consensys/skills (private overlay) instead. -->';

function runCli(args, env = {}) {
  return spawnSync(process.execPath, [BIN, ...args], {
    encoding: 'utf8',
    maxBuffer: 16 * 1024 * 1024,
    // Neutralize any source-dir env vars from the host shell so tests are deterministic.
    env: {
      ...process.env,
      METAMASK_SKILLS_DIR: '',
      CONSENSYS_SKILLS_DIR: '',
      SKILLS_PRUNE_STALE: '',
      ...env,
    },
  });
}

describe('CLI entrypoint', () => {
  test('--help prints usage and exits 0', () => {
    const result = runCli(['--help']);
    assert.equal(result.status, 0);
    assert.match(result.stdout, /MetaMask skills CLI/u);
    assert.match(result.stdout, /metamask-skills sync/u);
  });

  test('no command prints usage and exits 0', () => {
    const result = runCli([]);
    assert.equal(result.status, 0);
    assert.match(result.stdout, /Usage:/u);
  });

  test('unknown command exits 1 with error', () => {
    const result = runCli(['frobnicate']);
    assert.equal(result.status, 1);
    assert.match(result.stderr, /Unknown command: frobnicate/u);
  });

  test('runs when invoked through a symlinked bin (npm install layout)', () => {
    const dir = mkdtempSync(path.join(os.tmpdir(), 'mms-bin-'));
    const link = path.join(dir, 'metamask-skills');
    symlinkSync(BIN, link);
    const result = spawnSync(process.execPath, [link, '--help'], { encoding: 'utf8' });
    rmSync(dir, { recursive: true, force: true });
    assert.equal(result.status, 0);
    assert.match(result.stdout, /MetaMask skills CLI/u);
  });
});

describe('CLI list against a fixture source', () => {
  let root;
  let source;

  before(() => {
    root = mkdtempSync(path.join(os.tmpdir(), 'mms-cli-'));
    source = path.join(root, 'skills-source');
    const skillDir = path.join(source, 'domains', 'testing', 'skills', 'unit-testing');
    mkdirSync(path.join(skillDir, 'repos'), { recursive: true });
    mkdirSync(path.join(source, 'tools'), { recursive: true });
    writeFileSync(
      path.join(skillDir, 'skill.md'),
      ['---', 'name: unit-testing', 'description: Write unit tests', 'maturity: stable', '---', 'Body.'].join('\n'),
    );
  });

  after(() => {
    rmSync(root, { recursive: true, force: true });
  });

  test('list --json emits valid JSON scoped to the configured source', () => {
    const result = runCli(['list', '--json', '--target', root, '--repo', 'core'], {
      METAMASK_SKILLS_DIR: source,
    });
    assert.equal(result.status, 0);
    const parsed = JSON.parse(result.stdout);
    assert.equal(parsed.repo, 'core');
    assert.deepEqual(parsed.sources, [source]);
    assert.deepEqual(parsed.skills.map((s) => s.id), ['testing/unit-testing']);
  });

  test('search narrows results and exits 0', () => {
    const result = runCli(['search', 'unit', '--json', '--target', root], {
      METAMASK_SKILLS_DIR: source,
    });
    assert.equal(result.status, 0);
    const parsed = JSON.parse(result.stdout);
    assert.equal(parsed.skills.length, 1);
    assert.equal(parsed.query, 'unit');
  });
});

describe('managed skill pruning', () => {
  let root;
  let source;
  let target;

  before(() => {
    root = mkdtempSync(path.join(os.tmpdir(), 'mms-prune-'));
    source = path.join(root, 'source');
    target = path.join(root, 'target');
    const skillDir = path.join(source, 'domains', 'testing', 'skills', 'current');
    mkdirSync(skillDir, { recursive: true });
    mkdirSync(path.join(source, 'tools'), { recursive: true });
    symlinkSync(INSTALL, path.join(source, 'tools', 'install'));
    mkdirSync(target, { recursive: true });
    writeFileSync(
      path.join(skillDir, 'skill.md'),
      ['---', 'name: current', 'description: Current skill', 'maturity: stable', '---', 'Body.'].join('\n'),
    );
  });

  after(() => {
    rmSync(root, { recursive: true, force: true });
  });

  function writeInstalledSkill(base, name, file, managed, installTarget = target) {
    const dir = path.join(installTarget, base, name);
    mkdirSync(dir, { recursive: true });
    writeFileSync(path.join(dir, file), managed ? `${MANAGED_BANNER}\nBody.\n` : 'Hand-authored.\n');
    return dir;
  }

  test('removes only stale installer-managed skills across project targets', () => {
    const targets = [
      ['.claude/skills', 'SKILL.md'],
      ['.cursor/rules', 'RULE.md'],
      ['.agents/skills', 'SKILL.md'],
    ];
    const stale = [];
    const custom = [];
    for (const [base, file] of targets) {
      stale.push(writeInstalledSkill(base, 'mms-stale', file, true));
      custom.push(writeInstalledSkill(base, 'mms-custom', file, false));
    }

    const result = spawnSync(
      '/bin/bash',
      [INSTALL, '--target', target, '--repo', 'core', '--source', source, '--prune-stale'],
      { encoding: 'utf8' },
    );

    assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
    for (const dir of stale) assert.equal(existsSync(dir), false);
    for (const dir of custom) assert.equal(existsSync(dir), true);
    for (const [base] of targets) {
      assert.equal(existsSync(path.join(target, base, 'mms-current')), true);
    }
  });

  test('dry-run reports but preserves a stale managed skill', () => {
    const stale = writeInstalledSkill('.agents/skills', 'mms-dry-run-stale', 'SKILL.md', true);
    const result = spawnSync(
      '/bin/bash',
      [INSTALL, '--target', target, '--repo', 'core', '--source', source, '--prune-stale', '--dry-run'],
      { encoding: 'utf8' },
    );

    assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
    assert.match(result.stdout, /mms-dry-run-stale \(remove stale managed skill\)/u);
    assert.equal(existsSync(stale), true);
  });

  test('handles an empty expected selection under the supported system Bash', () => {
    const stale = writeInstalledSkill('.agents/skills', 'mms-empty-selection', 'SKILL.md', true);
    const result = spawnSync(
      '/bin/bash',
      [
        INSTALL,
        '--target',
        target,
        '--repo',
        'core',
        '--source',
        source,
        '--domain',
        'not-selected',
        '--prune-stale',
        '--dry-run',
      ],
      { encoding: 'utf8' },
    );

    assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
    assert.match(result.stdout, /mms-empty-selection \(remove stale managed skill\)/u);
    assert.equal(existsSync(stale), true);
  });

  test('wires prune through the public sync CLI flag and accepted environment values only', () => {
    const fromFlag = writeInstalledSkill('.agents/skills', 'mms-cli-flag-stale', 'SKILL.md', true);
    const flagResult = runCli(['sync', '--target', target, '--repo', 'core', '--prune-stale'], {
      METAMASK_SKILLS_DIR: source,
    });

    assert.equal(flagResult.status, 0, `${flagResult.stdout}\n${flagResult.stderr}`);
    assert.equal(existsSync(fromFlag), false);

    const fromEnv = writeInstalledSkill('.agents/skills', 'mms-cli-env-stale', 'SKILL.md', true);
    const envResult = runCli(['sync', '--target', target, '--repo', 'core'], {
      METAMASK_SKILLS_DIR: source,
      SKILLS_PRUNE_STALE: '1',
    });

    assert.equal(envResult.status, 0, `${envResult.stdout}\n${envResult.stderr}`);
    assert.equal(existsSync(fromEnv), false);

    const fromDisabledEnv = writeInstalledSkill('.agents/skills', 'mms-cli-disabled-env-stale', 'SKILL.md', true);
    const disabledEnvResult = runCli(['sync', '--target', target, '--repo', 'core'], {
      METAMASK_SKILLS_DIR: source,
      SKILLS_PRUNE_STALE: '0',
    });

    assert.equal(disabledEnvResult.status, 0, `${disabledEnvResult.stdout}\n${disabledEnvResult.stderr}`);
    assert.equal(existsSync(fromDisabledEnv), true);
  });

  test('does not prune stale skills when installation fails', () => {
    const failingTarget = path.join(root, 'failing-target');
    const stale = writeInstalledSkill('.agents/skills', 'mms-preserved-on-failure', 'SKILL.md', true, failingTarget);
    const blockingPath = path.join(failingTarget, '.claude', 'skills', 'mms-current');
    mkdirSync(path.dirname(blockingPath), { recursive: true });
    writeFileSync(blockingPath, 'Blocks creation of the managed skill directory.\n');

    const result = spawnSync(
      '/bin/bash',
      [INSTALL, '--target', failingTarget, '--repo', 'core', '--source', source, '--prune-stale'],
      { encoding: 'utf8' },
    );

    assert.notEqual(result.status, 0);
    assert.equal(existsSync(stale), true);
  });
});

describe('corpus: frontmatter cannot force a load', () => {
  // The permitted keys live in skill-frontmatter.json, not here — they describe the skill
  // FORMAT, so an author hitting this failure finds the list, and the reason a key is or is
  // not allowed, in a file they would think to open.
  //
  // Allowlist rather than a denylist of known-bad keys: a denylist silently exempts whatever
  // it did not name, so a key invented next month passes a check that knows only the old ones.
  const SCHEMA_PATH = path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    '..',
    'skill-frontmatter.json',
  );
  const SCHEMA = JSON.parse(readFileSync(SCHEMA_PATH, 'utf8'));
  const ALLOWED = {
    skill: new Set(Object.keys(SCHEMA.skill)),
    knowledge: new Set(Object.keys(SCHEMA.knowledge)),
  };

  function frontmatterKeys(body) {
    const m = /^---\n([\s\S]*?)\n---/u.exec(body);
    if (!m) return [];
    return m[1]
      .split('\n')
      .filter((l) => /^[A-Za-z_][\w-]*:/u.test(l)) // top-level only; nested lines are indented
      .map((l) => l.slice(0, l.indexOf(':')));
  }

  function corpusFiles() {
    const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
    const domainsDir = path.join(repoRoot, 'domains');
    const found = [];
    const walk = (dir) => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) walk(full);
        else if (entry.name === 'skill.md') found.push(['skill', full]);
        else if (entry.name.endsWith('.md') && full.includes(`${path.sep}knowledge${path.sep}`)) {
          found.push(['knowledge', full]);
        }
      }
    };
    walk(domainsDir);
    return found.map(([kind, full]) => ({
      kind,
      rel: path.relative(repoRoot, full).split(path.sep).join('/'),
      body: readFileSync(full, 'utf8'),
    }));
  }

  test('every frontmatter key is declared in skill-frontmatter.json', () => {
    const unknown = [];
    for (const { kind, rel, body } of corpusFiles()) {
      for (const key of frontmatterKeys(body)) {
        if (!ALLOWED[kind].has(key)) unknown.push(`${rel} → ${key} (${kind})`);
      }
    }
    assert.deepEqual(
      unknown,
      [],
      'frontmatter key not declared in skill-frontmatter.json. If it makes an agent load '
        + 'another file it must not be added — the context an agent ingests has to stay '
        + 'bounded. Otherwise declare it there, with a line saying what it does.',
    );
  });

  test('the schema declares every frontmatter key the installer reads', () => {
    // tools/install pulls specific keys by name. If it grows one the schema does not
    // declare, this fails rather than the installer quietly honouring an undeclared key.
    const install = readFileSync(
      path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'tools', 'install'),
      'utf8',
    );
    const read = [...install.matchAll(/frontmatter_value\s+"\$\w+"\s+"([\w-]+)"/gu)].map((m) => m[1]);
    assert.ok(read.length > 0, 'expected to find frontmatter_value calls in tools/install');
    const undeclared = [...new Set(read)].filter(
      (k) => !ALLOWED.skill.has(k) && !ALLOWED.knowledge.has(k),
    );
    assert.deepEqual(
      undeclared,
      [],
      'tools/install reads a frontmatter key that skill-frontmatter.json does not declare',
    );
  });
});
