name: Lint, Build, and Test

on:
  workflow_call:

jobs:
  validate-changelog:
    name: Validate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v2
        with:
          is-high-risk-environment: false
          cache-node-modules: true
          node-version: 24.x
      - run: yarn changelog:validate
      - name: Require clean working directory
        run: git diff --exit-code

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v2
        with:
          is-high-risk-environment: false
          cache-node-modules: true
          node-version: 24.x
      - run: yarn build
      - name: Require clean working directory
        run: git diff --exit-code

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v2
        with:
          is-high-risk-environment: false
          cache-node-modules: true
          node-version: ${{ matrix.node-version }}
      - run: yarn test
      - name: Require clean working directory
        run: git diff --exit-code

  pack:
    name: Pack dry run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v2
        with:
          is-high-risk-environment: false
          cache-node-modules: true
          node-version: 24.x
      - run: yarn pack:dry-run
      - name: Require clean working directory
        run: git diff --exit-code
